### ISSUE TITLE
counters get scaled by the flush interval

### ISSUE THREAD

**Issue by redterror** [quasor/statsd#1]
I noticed on line 38 of statsd/graphite.rb that you're scaling counters based on the size of the flush interval.  Is this intentional?  I noticed this because when I started using statsd in addition to an ad-hoc reporting system, there was a huge discrepancy (a factor a 60, it turned out).  The effect of that line is that the count that gets reported is effectively the average count for that interval, not the total.

It seems like the intent with counters is that if I have, say, 100 events that get collected during 1 flush interval, then statsd should send a value of 100 to graphite.  Is there another concern I'm not aware of?

Thanks!

**Comment by quasor** [comment]
I think you're right.

**Comment by tmm1** [comment]
What was the conclusion here? This appears to be what [etsy's statd](https://github.com/etsy/statsd/blob/master/stats.js#L71) does as well.

**Comment by quasor** [comment]
Which do you think is correct?

**Comment by redterror** [comment]
My expectation with this issue is that the "counters" stuff reflects the actual number of events received.  Scaling that by flush interval inflates the number, so then if you want accurate counts, you then have to do some extra step to undo this.

**Comment by tmm1** [comment]
This issue was fixed by bde280fda2ade308589794715a6d87af60ff77ac

Further investigation shows that etsy/statsd actually publishes two values per counter. The raw counter value is published the `stats_counts` namespace, whereas the `stats` namespace contains is a normalized "per second" value. I imagine they do this because the normalized graphs are slightly easier to understand (at noon, there were N exceptions per second), but there are definitely times where you want the raw value instead so they publish that separately.

The normalized value is easy to derive from the raw value (or the other way around) as long as the flush interval never changes. They probably publish both so they have flexibility over the flush interval.
